data(hoverflies)
data(hoverflies_INT)

# SC_spencer = shape_change(hoverflies,"year",method = "Spencer")
# SC_spencer_surr = shape_change(hoverflies,"year",method = "Spencer",surr = T)
# SC_ft = shape_change(hoverflies,"year",method = "Foster and Tilman")
# SC_jg = shape_change(hoverflies,"year",method = "Jassby and Goldman")
# SC_l = shape_change(hoverflies,"year",method = "Lewis")
# SC_bcf = shape_change(hoverflies,"year",method = "Bray Curtis Field")
# 
# SC_INT_spencer = shape_change(hoverflies_INT,"year",method = "Spencer")
# SC_INT_ft = shape_change(hoverflies_INT,"year",method = "Foster and Tilman")
# SC_INT_jg = shape_change(hoverflies_INT,"year",method = "Jassby and Goldman")
# SC_INT_l = shape_change(hoverflies_INT,"year",method = "Lewis")
# SC_INT_bcf = shape_change(hoverflies_INT,"year",method = "Bray Curtis Field")

SC_MCMC_spencer = shape_change(hoverflies_MCMC,"year",method = "Spencer",log_transform = T,mc_progress = T,iter = 4,mc_int=T)
SC_MCMC_ft = shape_change(hoverflies_MCMC,"year",method = "Foster and Tilman",log_transform = T,mc_progress = T,iter = 4)
SC_MCMC_jg = shape_change(hoverflies_MCMC,"year",method = "Jassby and Goldman",log_transform = T,mc_progress = T,iter = 4)
SC_MCMC_l = shape_change(hoverflies_MCMC,"year",method = "Lewis",log_transform = T,mc_progress = T,iter = 4)
SC_MCMC_bcf = shape_change(hoverflies_MCMC,"year",method = "Bray Curtis Field",log_transform = T,mc_progress = T,iter = 4)